### ISSUE TITLE
Submit your memes

### ISSUE THREAD

**Issue by nickneos** [nickneos/IT-Memes#1]
Follow instructions [here](https://github.com/nickneos/IT-Memes/blob/main/README.md) to submit your meme

**Comment by ZarghamDanial** [comment]
Hey, can i take up this?

**Comment by nickneos** [comment]
Yeah leaving this issue open for everyone 😸

**Comment by rzadev** [comment]
@nickneos I have created a pull request, please review it.

**Comment by Kiralinn** [comment]
Added a PR :D

**Comment by sayalitandel** [comment]
@nickneos I have created a pull request, this is my first ever PR of life. I would be glad if you review it! Thank you.
